# Generated by Django 4.0.3 on 2022-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_greeting_id_alter_greeting_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indicator1EntrancePrice', models.IntegerField()),
                ('Indicator1EntrancePlusMinus', models.IntegerField()),
                ('Indicator2EntrancePrice', models.IntegerField()),
                ('Indicator2EntrancePlusMinus', models.IntegerField()),
            ],
        ),
    ]
