# Generated by Django 4.0.3 on 2022-04-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_inputrange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inputRange',
        ),
    ]
